/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package VISTA;

import CONTROLADOR.CONTROLADOR_Matricula;
import CONTROLADOR.CONTROLADOR_Curso;
import MODELO.*;
import UTIL.GeneradorPDF;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.util.List;
import java.awt.Desktop;

/**
 * Ventana para generar reportes y constancias en PDF
 * @author MartinSoftware
 */
public class VISTA_Reportes extends javax.swing.JDialog {

    private MODELO_Usuario usuarioLogueado;
    private CONTROLADOR_Matricula controladorMatricula;
    private CONTROLADOR_Curso controladorCurso;
    private List<MODELO_Curso> listaCursos;
    
    /**
     * Constructor
     * @param parent ventana padre
     * @param modal si es modal
     * @param usuario usuario logueado
     */
    public VISTA_Reportes(java.awt.Frame parent, boolean modal, MODELO_Usuario usuario) {
        super(parent, modal);
        initComponents();
        
        this.usuarioLogueado = usuario;
        this.controladorMatricula = new CONTROLADOR_Matricula();
        this.controladorCurso = new CONTROLADOR_Curso();
        
        configurarVentana();
        cargarCursos();
    }
    
    /**
     * Configurar ventana
     */
    private void configurarVentana() {
        this.setLocationRelativeTo(null);
        this.setTitle("Reportes y Constancias - Academia de Belleza");
        btnGenerarConstancia.setEnabled(false);
    }
    
    /**
     * Cargar cursos en el ComboBox
     */
    private void cargarCursos() {
        cboCurso.removeAllItems();
        listaCursos = controladorCurso.listarActivos();
        
        if (listaCursos.isEmpty()) {
            cboCurso.addItem("No hay cursos disponibles");
            cboCurso.setEnabled(false);
            btnReporteCurso.setEnabled(false);
        } else {
            cboCurso.addItem("-- Seleccione un curso --");
            for (MODELO_Curso curso : listaCursos) {
                String item = curso.getNombreCurso() + " - " + curso.getNivel();
                cboCurso.addItem(item);
            }
            cboCurso.setSelectedIndex(0);
        }
    }
    
    /**
     * Obtener ruta donde guardar el PDF
     * @param nombreArchivo nombre sugerido para el archivo
     * @return ruta completa del archivo o null si cancela
     */
    private String obtenerRutaGuardado(String nombreArchivo) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar Reporte PDF");
        fileChooser.setSelectedFile(new File(nombreArchivo));
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos PDF (*.pdf)", "pdf");
        fileChooser.setFileFilter(filter);
        
        int result = fileChooser.showSaveDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();
            
            // Agregar extensión .pdf si no la tiene
            if (!ruta.toLowerCase().endsWith(".pdf")) {
                ruta += ".pdf";
            }
            
            return ruta;
        }
        
        return null;
    }
    
    /**
     * Abrir el archivo PDF generado
     * @param rutaArchivo ruta del archivo
     */
    private void abrirPDF(String rutaArchivo) {
        try {
            File archivo = new File(rutaArchivo);
            if (archivo.exists()) {
                if (Desktop.isDesktopSupported()) {
                    Desktop.getDesktop().open(archivo);
                } else {
                    JOptionPane.showMessageDialog(this, 
                        "PDF generado correctamente en:\n" + rutaArchivo, 
                        "Éxito", 
                        JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e) {
            System.err.println("Error al abrir PDF: " + e.getMessage());
            JOptionPane.showMessageDialog(this, 
                "PDF generado correctamente en:\n" + rutaArchivo + 
                "\n\nNo se pudo abrir automáticamente.", 
                "Información", 
                JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtCodigoMatricula = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnReporteMatriculas = new javax.swing.JButton();
        btnListaMatricula = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cboCurso = new javax.swing.JComboBox<>();
        btnGenerarConstancia = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        btnReporteCurso = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        btnReporteCursos = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnBuscarMatricula = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Asociación Privada de Patronato");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REPORTES Y CONSTANCIAS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("SELECCIONAR CURSO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, 10));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 20, 370));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("REPORTE DE ESTUDIANTES POR CURSO ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 370, 10));

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("CONSTANCIA DE MATRÍCULA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtCodigoMatricula.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoMatricula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodigoMatricula.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigoMatricula.setBorder(null);
        jPanel1.add(txtCodigoMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 300, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 300, 20));

        btnReporteMatriculas.setBackground(new java.awt.Color(255, 255, 153));
        btnReporteMatriculas.setForeground(new java.awt.Color(0, 0, 0));
        btnReporteMatriculas.setText("GENERAR REPORTE GENERAL");
        btnReporteMatriculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteMatriculasActionPerformed(evt);
            }
        });
        jPanel1.add(btnReporteMatriculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 300, 40));

        btnListaMatricula.setBackground(new java.awt.Color(153, 255, 153));
        btnListaMatricula.setForeground(new java.awt.Color(0, 0, 0));
        btnListaMatricula.setText("LISTA DE MATRICULAS");
        btnListaMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaMatriculaActionPerformed(evt);
            }
        });
        jPanel1.add(btnListaMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 180, 40));

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("CÓDIGO DE MATRÍCULA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jPanel1.add(cboCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 360, -1));

        btnGenerarConstancia.setBackground(new java.awt.Color(255, 153, 153));
        btnGenerarConstancia.setForeground(new java.awt.Color(0, 0, 0));
        btnGenerarConstancia.setText("GENERAR CONSTANCIA");
        btnGenerarConstancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarConstanciaActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerarConstancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 300, 30));

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 770, 10));

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("REPORTE DE CURSOS ACTIVOS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 280, 10));

        btnReporteCurso.setBackground(new java.awt.Color(204, 255, 153));
        btnReporteCurso.setForeground(new java.awt.Color(0, 0, 0));
        btnReporteCurso.setText("GENERAR REPORTE");
        btnReporteCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteCursoActionPerformed(evt);
            }
        });
        jPanel1.add(btnReporteCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 180, 40));

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("REPORTE GENERAL DE MATRÍCULAS");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 370, 10));

        btnReporteCursos.setBackground(new java.awt.Color(153, 153, 255));
        btnReporteCursos.setForeground(new java.awt.Color(0, 0, 0));
        btnReporteCursos.setText("GENERAR LISTADO");
        btnReporteCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteCursosActionPerformed(evt);
            }
        });
        jPanel1.add(btnReporteCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 300, 40));

        btnCerrar.setBackground(new java.awt.Color(255, 102, 102));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrar.setText("CANCELAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 280, 40));

        btnBuscarMatricula.setBackground(new java.awt.Color(102, 204, 255));
        btnBuscarMatricula.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarMatricula.setText("BUSCAR");
        btnBuscarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMatriculaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();        
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnListaMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaMatriculaActionPerformed
        
        // Abrir ventana buscadora
        VISTA_BuscadorMatriculas buscador = new VISTA_BuscadorMatriculas(
            (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this), 
            true
        );
        buscador.setVisible(true);

        // Obtener código seleccionado
        String codigoSeleccionado = buscador.getCodigoMatriculaSeleccionado();

        if (codigoSeleccionado != null) {
            // Llenar el campo automáticamente
            txtCodigoMatricula.setText(codigoSeleccionado);

            // Simular clic en buscar para validar
            btnBuscarMatriculaActionPerformed(null);

            JOptionPane.showMessageDialog(this, 
                "Matrícula seleccionada: " + codigoSeleccionado + "\n" +
                "Ya puede generar la constancia", 
                "Matrícula Cargada", 
                JOptionPane.INFORMATION_MESSAGE);
        }



    }//GEN-LAST:event_btnListaMatriculaActionPerformed

    private void btnGenerarConstanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarConstanciaActionPerformed
        // TODO add your handling code here:
        String codigoMatricula = txtCodigoMatricula.getText().trim();
        
        if (codigoMatricula.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor busque una matrícula primero", 
                "Validación", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Buscar matrícula completa
        MODELO_Matricula matricula = controladorMatricula.buscarMatriculaPorCodigo(codigoMatricula);
        
        if (matricula == null) {
            JOptionPane.showMessageDialog(this, 
                "Error al obtener los datos de la matrícula", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Buscar estudiante
        MODELO_Estudiante estudiante = controladorMatricula.buscarEstudiantePorId(matricula.getIdEstudiante());
        
        if (estudiante == null) {
            JOptionPane.showMessageDialog(this, 
                "Error al obtener los datos del estudiante", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Buscar curso
        MODELO_Curso curso = controladorMatricula.buscarCursoPorId(matricula.getIdCurso());
        
        if (curso == null) {
            JOptionPane.showMessageDialog(this, 
                "Error al obtener los datos del curso", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Obtener ruta de guardado
        String nombreArchivo = "Constancia_" + codigoMatricula + ".pdf";
        String rutaArchivo = obtenerRutaGuardado(nombreArchivo);
        
        if (rutaArchivo == null) {
            return; // Usuario canceló
        }
        
        // Generar PDF
        boolean resultado = GeneradorPDF.generarConstanciaMatricula(matricula, estudiante, curso, rutaArchivo);
        
        if (resultado) {
            JOptionPane.showMessageDialog(this, 
                "Constancia generada exitosamente", 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);
            
            abrirPDF(rutaArchivo);
        } else {
            JOptionPane.showMessageDialog(this, 
                "Error al generar la constancia", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnGenerarConstanciaActionPerformed

    private void btnReporteCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteCursoActionPerformed
        // TODO add your handling code here:
        int indexCurso = cboCurso.getSelectedIndex();
        
        if (indexCurso <= 0) {
            JOptionPane.showMessageDialog(this, 
                "Por favor seleccione un curso", 
                "Validación", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Obtener curso seleccionado
        MODELO_Curso curso = listaCursos.get(indexCurso - 1);
        
        // Obtener matrículas del curso
        List<MODELO_Matricula> matriculas = controladorMatricula.listarMatriculasPorCurso(curso.getIdCurso());
        
        if (matriculas.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "El curso no tiene estudiantes matriculados", 
                "Información", 
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        // Obtener ruta de guardado
        String nombreArchivo = "Reporte_" + curso.getNombreCurso().replace(" ", "_") + ".pdf";
        String rutaArchivo = obtenerRutaGuardado(nombreArchivo);
        
        if (rutaArchivo == null) {
            return;
        }
        
        // Generar PDF
        boolean resultado = GeneradorPDF.generarReporteEstudiantesPorCurso(curso, matriculas, rutaArchivo);
        
        if (resultado) {
            JOptionPane.showMessageDialog(this, 
                "Reporte generado exitosamente\n" +
                "Total de estudiantes: " + matriculas.size(), 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);
            
            abrirPDF(rutaArchivo);
        } else {
            JOptionPane.showMessageDialog(this, 
                "Error al generar el reporte", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnReporteCursoActionPerformed

    private void btnReporteCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteCursosActionPerformed
        // TODO add your handling code here:
        // Obtener todos los cursos activos
        List<MODELO_Curso> cursos = controladorCurso.listarActivos();
        
        if (cursos.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "No hay cursos activos para generar el reporte", 
                "Información", 
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        // Obtener ruta de guardado
        String nombreArchivo = "Listado_Cursos_Activos.pdf";
        String rutaArchivo = obtenerRutaGuardado(nombreArchivo);
        
        if (rutaArchivo == null) {
            return;
        }
        
        // Generar PDF
        boolean resultado = GeneradorPDF.generarListadoCursosActivos(cursos, rutaArchivo);
        
        if (resultado) {
            JOptionPane.showMessageDialog(this, 
                "Listado generado exitosamente\n" +
                "Total de cursos: " + cursos.size(), 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);
            
            abrirPDF(rutaArchivo);
        } else {
            JOptionPane.showMessageDialog(this, 
                "Error al generar el listado", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnReporteCursosActionPerformed

    private void btnReporteMatriculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteMatriculasActionPerformed
        // TODO add your handling code here:
        // Obtener todas las matrículas
        List<MODELO_Matricula> matriculas = controladorMatricula.listarTodasMatriculas();
        
        if (matriculas.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "No hay matrículas registradas para generar el reporte", 
                "Información", 
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        // Obtener ruta de guardado
        String nombreArchivo = "Reporte_General_Matriculas.pdf";
        String rutaArchivo = obtenerRutaGuardado(nombreArchivo);
        
        if (rutaArchivo == null) {
            return;
        }
        
        // Generar PDF
        boolean resultado = GeneradorPDF.generarReporteGeneralMatriculas(matriculas, rutaArchivo);
        
        if (resultado) {
            JOptionPane.showMessageDialog(this, 
                "Reporte generado exitosamente\n" +
                "Total de matrículas: " + matriculas.size(), 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);
            
            abrirPDF(rutaArchivo);
        } else {
            JOptionPane.showMessageDialog(this, 
                "Error al generar el reporte", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnReporteMatriculasActionPerformed

    private void btnBuscarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMatriculaActionPerformed
        // TODO add your handling code here:
        String codigoMatricula = txtCodigoMatricula.getText().trim();
        
        if (codigoMatricula.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor ingrese el código de matrícula", 
                "Validación", 
                JOptionPane.WARNING_MESSAGE);
            txtCodigoMatricula.requestFocus();
            return;
        }
        
        // Buscar matrícula
        MODELO_Matricula matricula = controladorMatricula.buscarMatriculaPorCodigo(codigoMatricula);
        
        if (matricula == null) {
            JOptionPane.showMessageDialog(this, 
                "No se encontró ninguna matrícula con el código: " + codigoMatricula, 
                "No encontrado", 
                JOptionPane.WARNING_MESSAGE);
            btnGenerarConstancia.setEnabled(false);
            return;
        }
        
        // Matrícula encontrada
        JOptionPane.showMessageDialog(this, 
            "Matrícula encontrada:\n\n" +
            "Estudiante: " + matricula.getNombreEstudiante() + "\n" +
            "Curso: " + matricula.getNombreCurso() + " - " + matricula.getNivelCurso() + "\n" +
            "Estado: " + matricula.getEstado(), 
            "Matrícula Encontrada", 
            JOptionPane.INFORMATION_MESSAGE);
        
        btnGenerarConstancia.setEnabled(true);
    }//GEN-LAST:event_btnBuscarMatriculaActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarMatricula;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGenerarConstancia;
    private javax.swing.JButton btnListaMatricula;
    private javax.swing.JButton btnReporteCurso;
    private javax.swing.JButton btnReporteCursos;
    private javax.swing.JButton btnReporteMatriculas;
    private javax.swing.JComboBox<String> cboCurso;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField txtCodigoMatricula;
    // End of variables declaration//GEN-END:variables
}
