/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

import MODELO.MODELO_Usuario;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author MartinSoftware
 */
public class VISTA_PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VISTA_PantallaPrincipal
     */
    private MODELO_Usuario usuarioLogueado;

    public VISTA_PantallaPrincipal(MODELO_Usuario usuario) {
        initComponents();
        this.usuarioLogueado = usuario;
        //configurarVentana();
        mostrarDatosUsuario();
        configurarAccesosPorRol();
        configurarTooltips();
        configurarEfectosHover();
        iniciarReloj();
    }

    private void configurarVentana() {
        this.setLocationRelativeTo(null); // Centrar
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); // Pantalla completa
    }

    /**
     * Mostrar datos del usuario logueado
     */
    private void mostrarDatosUsuario() {
        // Si tienes un JLabel para mostrar el nombre del usuario
        lblUsuario.setText(usuarioLogueado.getNombreCompleto());
        lblRol.setText(usuarioLogueado.getRol());

        System.out.println("✓ Pantalla principal abierta");
        System.out.println("  Usuario: " + usuarioLogueado.getNombreCompleto());
        System.out.println("  Rol: " + usuarioLogueado.getRol());
    }

    private void configurarAccesosPorRol() {
        // Si el usuario es RECEPCIONISTA, ocultar el módulo de Accesos
        if ("RECEPCIONISTA".equals(usuarioLogueado.getRol())) {
            btnAccesos.setEnabled(false);
            btnAccesos.setToolTipText("No tiene permisos para acceder a este módulo");
        }

        // Puedes agregar más restricciones según el rol
        // Por ejemplo:
        // if ("RECEPCIONISTA".equals(usuarioLogueado.getRol())) {
        //     btnReportes.setEnabled(false);
        // }
    }

    private void iniciarReloj() {
        Timer timer = new Timer(1000, e -> {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            lblFechaHora.setText(sdf.format(new Date()));
        });
        timer.start();
    }
    private void configurarTooltips() {
        btnNuevaMatricula.setToolTipText("Registrar nueva matrícula de estudiante");
        btnGestionCursos.setToolTipText("Administrar cursos disponibles");
        btnGestionDocentes.setToolTipText("Gestionar docentes de la academia");
        btnGestionEstudiantes.setToolTipText("Ver y modificar datos de estudiantes");
        btnReportes.setToolTipText("Generar reportes y constancias");
        btnAccesos.setToolTipText("Gestionar usuarios del sistema");
    }

    private void configurarEfectosHover() {
        // Color original de los botones
        Color colorOriginal = btnNuevaMatricula.getBackground();
        Color colorOriginalAcceso = btnAccesos.getBackground();
        Color colorHover = new Color(52, 152, 219); // Azul más claro

        // Aplicar efecto a cada botón
        aplicarEfectoHover(btnNuevaMatricula, colorOriginal, colorHover);
        aplicarEfectoHover(btnGestionCursos, colorOriginal, colorHover);
        aplicarEfectoHover(btnGestionDocentes, colorOriginal, colorHover);
        aplicarEfectoHover(btnGestionEstudiantes, colorOriginal, colorHover);
        aplicarEfectoHover(btnReportes, colorOriginal, colorHover);
        aplicarEfectoHover(btnAccesos, colorOriginalAcceso, colorHover);
    }
    
    private void aplicarEfectoHover(javax.swing.JButton boton, Color colorOriginal, Color colorHover) {
    boton.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            boton.setBackground(colorHover);
            boton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
        
        @Override
        public void mouseExited(MouseEvent e) {
            boton.setBackground(colorOriginal);
            boton.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblRol12 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        lblFechaHo = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        lblFechaHora = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnGestionDocentes = new javax.swing.JButton();
        btnNuevaMatricula = new javax.swing.JButton();
        btnGestionCursos = new javax.swing.JButton();
        btnAccesos = new javax.swing.JButton();
        btnGestionEstudiantes = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(38, 70, 83));

        jPanel2.setBackground(new java.awt.Color(29, 53, 87));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Asociación Privada de Patronato");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 430, 20));

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SISTEMA DIGITAL DE MATRÍCULA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 520, 30));

        lblUsuario.setBackground(new java.awt.Color(0, 0, 0));
        lblUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("USER");
        jPanel2.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 6, 170, 20));

        lblRol12.setBackground(new java.awt.Color(0, 0, 0));
        lblRol12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblRol12.setForeground(new java.awt.Color(255, 255, 255));
        lblRol12.setText("ROL:");
        jPanel2.add(lblRol12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, -1));

        btnCerrarSesion.setBackground(new java.awt.Color(255, 102, 102));
        btnCerrarSesion.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 180, 41));

        lblFechaHo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblFechaHo.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaHo.setText("FECHA:\n");
        jPanel2.add(lblFechaHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 60, 20));

        lblUsuario1.setBackground(new java.awt.Color(0, 0, 0));
        lblUsuario1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario1.setText("USUARIO:");
        jPanel2.add(lblUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 6, 80, 20));

        lblRol.setBackground(new java.awt.Color(0, 0, 0));
        lblRol.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblRol.setForeground(new java.awt.Color(255, 255, 255));
        lblRol.setText("[ROL]");
        jPanel2.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 30, 170, -1));

        lblFechaHora.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFechaHora.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaHora.setText("[RELOJ]");
        jPanel2.add(lblFechaHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 200, 20));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));

        btnGestionDocentes.setBackground(new java.awt.Color(241, 250, 238));
        btnGestionDocentes.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnGestionDocentes.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionDocentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTIL/imagenes/docentes.png"))); // NOI18N
        btnGestionDocentes.setText("DOCENTES");
        btnGestionDocentes.setBorder(null);
        btnGestionDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionDocentesActionPerformed(evt);
            }
        });

        btnNuevaMatricula.setBackground(new java.awt.Color(241, 250, 238));
        btnNuevaMatricula.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnNuevaMatricula.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevaMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTIL/imagenes/matricula.png"))); // NOI18N
        btnNuevaMatricula.setText("MATRICULAS");
        btnNuevaMatricula.setBorder(null);
        btnNuevaMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaMatriculaActionPerformed(evt);
            }
        });

        btnGestionCursos.setBackground(new java.awt.Color(241, 250, 238));
        btnGestionCursos.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnGestionCursos.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTIL/imagenes/curso-por-internet.png"))); // NOI18N
        btnGestionCursos.setText("CURSOS");
        btnGestionCursos.setBorder(null);
        btnGestionCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionCursosActionPerformed(evt);
            }
        });

        btnAccesos.setBackground(new java.awt.Color(244, 162, 97));
        btnAccesos.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        btnAccesos.setForeground(new java.awt.Color(0, 0, 0));
        btnAccesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTIL/imagenes/no-autorizado.png"))); // NOI18N
        btnAccesos.setText("ACCESOS AUTORIZADOS");
        btnAccesos.setBorder(null);
        btnAccesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccesosActionPerformed(evt);
            }
        });

        btnGestionEstudiantes.setBackground(new java.awt.Color(241, 250, 238));
        btnGestionEstudiantes.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnGestionEstudiantes.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTIL/imagenes/students.png"))); // NOI18N
        btnGestionEstudiantes.setText("ESTUDIANTES");
        btnGestionEstudiantes.setBorder(null);
        btnGestionEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionEstudiantesActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(241, 250, 238));
        btnReportes.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(0, 0, 0));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTIL/imagenes/reportes.png"))); // NOI18N
        btnReportes.setText("REPORTES Y CONSTANCIAS");
        btnReportes.setBorder(null);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Proyecto como parte del Curso Integrador 1 - Sistemas | Software");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTIL/imagenes/logo utp.jpg"))); // NOI18N

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNuevaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGestionCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGestionDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAccesos, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestionDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAccesos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGestionEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro que desea cerrar sesión?",
                "Confirmar Cierre de Sesión",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            System.out.println("✓ Cerrando sesión de: " + usuarioLogueado.getUsername());

            // Cerrar ventana actual
            this.dispose();

            // Abrir nuevamente el Login
            VISTA_Login login = new VISTA_Login();
            login.setVisible(true);
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnNuevaMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaMatriculaActionPerformed
        // TODO add your handling code here:
        System.out.println("✓ Abriendo módulo de Matrícula...");

        VISTA_Matricula ventana = new VISTA_Matricula(usuarioLogueado);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnNuevaMatriculaActionPerformed

    private void btnGestionCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionCursosActionPerformed
        System.out.println("✓ Abriendo módulo de Cursos...");
    
        VISTA_GestionCursos ventana = new VISTA_GestionCursos(usuarioLogueado);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnGestionCursosActionPerformed

    private void btnGestionDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionDocentesActionPerformed
        // TODO add your handling code here:
                System.out.println("✓ Abriendo módulo de Docentes...");
    
        // Reemplaza el mensaje temporal con esto:
        VISTA_GestionDocentes ventana = new VISTA_GestionDocentes(usuarioLogueado);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnGestionDocentesActionPerformed

    private void btnGestionEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionEstudiantesActionPerformed
        // TODO add your handling code here:
        System.out.println("✓ Abriendo módulo de Estudiantes...");
        VISTA_GestionEstudiantes ventana = new VISTA_GestionEstudiantes(usuarioLogueado);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnGestionEstudiantesActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        System.out.println("✓ Abriendo módulo de Reportes...");
    
        VISTA_Reportes ventana = new VISTA_Reportes(this, true, usuarioLogueado);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnAccesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccesosActionPerformed
        System.out.println("✓ Abriendo módulo de Accesos...");
    
        VISTA_GestionAccesos ventana = new VISTA_GestionAccesos(usuarioLogueado);
        ventana.setVisible(true);
        
    }//GEN-LAST:event_btnAccesosActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccesos;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGestionCursos;
    private javax.swing.JButton btnGestionDocentes;
    private javax.swing.JButton btnGestionEstudiantes;
    private javax.swing.JButton btnNuevaMatricula;
    private javax.swing.JButton btnReportes;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblFechaHo;
    private javax.swing.JLabel lblFechaHora;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblRol12;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    // End of variables declaration//GEN-END:variables
}
